name: withapp_did
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.24

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0
  go_router: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  retrofit: ^3.3.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
#  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/
  fonts:
    - family: Noto_Sans_KR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKr-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKr-Light.otf
          weight: 200
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKr-Regular.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKr-Medium.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKr-Bold.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKr-Black.otf
          weight: 600

    - family: 210_OmniGothic
      fonts:
        - asset: assets/fonts/210_OmniGothic/210_OmniGothic_010.otf
          weight: 100
        - asset: assets/fonts/210_OmniGothic/210_OmniGothic_020.otf
          weight: 200
        - asset: assets/fonts/210_OmniGothic/210_OmniGothic_030.otf
          weight: 300
        - asset: assets/fonts/210_OmniGothic/210_OmniGothic_040.otf
          weight: 400
        - asset: assets/fonts/210_OmniGothic/210_OmniGothic_050.otf
          weight: 500

    - family: 210_MGothic
      fonts:
        - asset: assets/fonts/210_MGothic/210_MGothic_010.otf
          weight: 100
        - asset: assets/fonts/210_MGothic/210_MGothic_020.otf
          weight: 200
        - asset: assets/fonts/210_MGothic/210_MGothic_030.otf
          weight: 300
        - asset: assets/fonts/210_MGothic/210_MGothic_040.otf
          weight: 400
        - asset: assets/fonts/210_MGothic/210_MGothic_050.otf
          weight: 500
        - asset: assets/fonts/210_MGothic/210_MGothic_060.otf
          weight: 600
        - asset: assets/fonts/210_MGothic/210_MGothic_070.otf
          weight: 700
        - asset: assets/fonts/210_MGothic/210_MGothic_080.otf
          weight: 800
        - asset: assets/fonts/210_MGothic/210_MGothic_090.otf
          weight: 900

    - family: KoPubDotum
      fonts:
        - asset: assets/fonts/ko_pub_dotum/KoPubDotumBold.ttf
          weight: 800
        - asset: assets/fonts/ko_pub_dotum/KoPubDotumMedium.ttf
          weight: 500
        - asset: assets/fonts/ko_pub_dotum/KoPubDotumLight.ttf
          weight: 200