name: withapp_did
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.24

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0
  go_router: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  permission_handler: ^10.2.0
  retrofit: ^3.3.1
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
#  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/
  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeoOTF-aLt.otf
          weight: 200
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeoOTF-bRg.otf
          weight: 300
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeoOTF-cBd.otf
          weight: 400
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeoOTF-dEb.otf
          weight: 500
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeoOTF-eHv.otf
          weight: 600